export {
  PAGE_ACTION_REQUEST_EVENT,
  PAGE_ACTION_RESPONSE_EVENT,
  BACKGROUND_ACTION_REQUEST_EVENT,
  BACKGROUND_ACTION_RESPONSE_EVENT,
  DEFAULT_ACTION_TIMEOUT,
} from '@/shared/bridge/constants';
